let adjective = "Big";
let noun = "Dragon";
let verb = "angry";
let place = "cave";
let adjective2 = "red";
let noun2 = "livestock";
let firstStory = "Once upon a time, there was a(n) " + adjective + " " + noun + " who loved to eat " + noun2 + "." + " The " + noun + " lived in a " + place + " and had " + adjective2 +  " nostrils that blew fire when it was " + verb + ".";
console.log("First story: " + firstStory);
adjective = "Cute";
noun = "Bunny";
verb = "happy";
place = "farm";
adjective2 = "pink";
noun2 = "carrots";
let secondStory = "Once upon a time, there was a(n) " + adjective + " " + noun + " who loved to eat " + noun2 + "." + " The " + noun + " lived in a " + place + " and had " + adjective2 +  " nostrils that blew fire when it was " + verb + ".";
console.log("Second story: " + secondStory);